# Generated by Django 3.2.4 on 2021-07-07 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('desc', models.TextField(max_length=1000)),
                ('time', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
